### ISSUE TITLE
UI Changes and few additions - Hacktoberfest

### ISSUE THREAD

**Issue by Nitish36** [SyedImtiyaz-1/Code-Shop#2]
Hey there I would like to add a few changes to the UI and also make the nav bar user-friendly that is when the user clicks on any button in the navbar should direct him to that particular tab. Please assign this issue under hacktoberfest-accepted

**Comment by Prakharpandey007** [comment]
please assign this issue . Looking for the positive issue.
Thank You,

**Comment by Nitish36** [comment]
Sorry the maintainer has assigned this issue to me and I am working on this and almost done. You make look for some other thing

Thank you :)

**Comment by Nitish36** [comment]
![image](https://github.com/SyedImtiyaz-1/Code-Shop/assets/91598274/caa7a599-b3c5-410e-a53e-4f790dc2376f)
![image](https://github.com/SyedImtiyaz-1/Code-Shop/assets/91598274/45cab8f0-dd17-4b9c-b296-4fdb76169f23)
![image](https://github.com/SyedImtiyaz-1/Code-Shop/assets/91598274/8e320f91-54ad-4958-9479-42dadf2147ca)
![image](https://github.com/SyedImtiyaz-1/Code-Shop/assets/91598274/6e42d198-d35d-4332-9900-9a8e11815781)
![image](https://github.com/SyedImtiyaz-1/Code-Shop/assets/91598274/615aa680-21cd-4993-8b2c-3928712d7145)
![image](https://github.com/SyedImtiyaz-1/Code-Shop/assets/91598274/138359cf-3533-4a12-bfa6-b31ac36d389e)
![image](https://github.com/SyedImtiyaz-1/Code-Shop/assets/91598274/5e011705-f63c-40cd-8a61-d6252486a6c8)

**Comment by Nitish36** [comment]
These are the outputs hopefully you will like them :)

**Comment by 07tAnYa** [comment]
Kindly assign this to me, I can add more features to this
