### ISSUE TITLE
back to top arrow got disabled 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [SyedImtiyaz-1/Code-Shop#70]
Hello Contributors,
Please add back to top arrow 👍🏻 
![image](https://github.com/SyedImtiyaz-1/Code-Shop/assets/121503426/ff43d7b7-066c-492c-a308-1c6d94e4d46e)

which is in the right bottom side.

**Comment by Nchhabra25** [comment]
Hey, I would like to work on this! Pls assign it to me

**Comment by Nchhabra25** [comment]
Hi ! I noticed that the issue was reopened. Could you please provide some context on why it was reopened and if there are any specific concerns or changes that need to be made? I'm more than happy to work on resolving the issue further and ensuring it meets the project's requirements.

**Comment by Logesh-waran2003** [comment]
I would like to work on this and make it as you requested. Please assign this to me (Hacktoberfest).
